trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
  
steps:
- checkout: self
  clean: true
  persistCredentials: true

- script: |
    git fetch --all
    git switch `basename $(Build.SourceBranch)`

- script: curl -L 'https://spectral-us.checkpoint.com/latest/x/sh?dsn=$(SPECTRAL_DSN)' | sh
  displayName: 'Install Spectral'
- script: $HOME/.spectral/spectral scan --ok --dsn $(SPECTRAL_DSN) --engines secrets,iac,oss --include-tags base,audit3,iac
  displayName: 'Spectral Scan'
# ShiftLeft Container Image Scan stage
- script: |
    chmod +x ./shiftleft
    ./shiftleft image-scan -e 94fddd65-708a-4dc1-bac8-002fd35e34bf -i web.tar
  displayName: 'ShiftLeft Container Image Scan'
  continueOnError: true  # Permite que continúe aunque el escaneo falle