version: '3.1'
services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
